CREATE DATABASE TimeCo
USE TimeCo

CREATE TABLE Roles (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] VARCHAR(50)  NOT NULL,
[Description] VARCHAR(250)  NOT NULL
)

CREATE TABLE Departments (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] VARCHAR(50)  NOT NULL,
[Description] VARCHAR(250)  NOT NULL
)

CREATE TABLE Users(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
[Password] VARCHAR(250) NOT NULL,
Username VARCHAR(50) NOT NULL,
CreatedAt DATETIME2 NOT NULL,
ModifiedAt DATETIME2 NOT NULL,
MainVacationHours FLOAT DEFAULT(200) NOT NULL,
RoleID INT NOT NULL,
DepartmentID INT NOT NULL,
FOREIGN KEY (RoleID) REFERENCES Roles(Id),
FOREIGN KEY (DepartmentID) REFERENCES Departments(Id),
)

CREATE TABLE Schedules (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Shift] VARCHAR(50) NOT NULL,
StartDate DATETIME2 NOT NULL,
EndDate DATETIME2 NOT NULL,
StartHour TIME NOT NULL,
EndHour TIME NOT NULL,
UserID INT NOT NULL,
FOREIGN KEY (UserID) REFERENCES Users(Id)
)

CREATE TABLE Vacations (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] VARCHAR(50) NOT NULL,
[Description] VARCHAR(250) NOT NULL,
[Status] VARCHAR(50) NOT NULL,
StartDate DATETIME2 NOT NULL,
EndDate DATETIME2 NOT NULL,
isMainVacation BIT NOT NULL,
UserID INT NOT NULL,
FOREIGN KEY (UserID) REFERENCES Users(Id)
)



INSERT INTO Roles([Name], [Description])
VALUES ('Admin', 'Administrator - Boss')

INSERT INTO Roles([Name], [Description])
VALUES ('Standard', 'Standard user - Worker')

INSERT INTO Departments([Name], [Description])
VALUES ('Engineering', 'Technical division for engineering work')

INSERT INTO Departments([Name], [Description])
VALUES ('Hardware', 'Division handling physical computer components.')

INSERT INTO Users (FirstName, LastName, Email, [Password], Username, CreatedAt, ModifiedAt, RoleID, DepartmentID)
VALUES ('Teodora', 'Kompanska', 'tkompanska@gmail.com', '54C645DE9376C8BC40416CBF368CD12185902FB37A6AD079507D6B829711DF3E66023ED6967D0B9AC61E066CC38794C281F4D3D1FF9E7E06435302F30C7696DE', 'kompanska', GETDATE(), GETDATE(), 1, 1)

INSERT INTO Users (FirstName, LastName, Email, [Password], Username, CreatedAt, ModifiedAt, RoleID, DepartmentID)
VALUES ('Maria', 'Ivanova', 'mivanova@gmail.com', '54C645DE9376C8BC40416CBF368CD12185902FB37A6AD079507D6B829711DF3E66023ED6967D0B9AC61E066CC38794C281F4D3D1FF9E7E06435302F30C7696DE', 'mivanova', GETDATE(), GETDATE(), 2, 1)