CREATE DATABASE TimeCo
USE TimeCo

CREATE TABLE Roles (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] VARCHAR(50)  NOT NULL,
[Description] VARCHAR(250)  NOT NULL
)

CREATE TABLE Departments (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] VARCHAR(50)  NOT NULL,
[Description] VARCHAR(250)  NOT NULL
)

CREATE TABLE Users(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
[Password] VARCHAR(250) NOT NULL,
Username VARCHAR(50) NOT NULL,
CreatedAt DATETIME2 NOT NULL,
ModifiedAt DATETIME2 NOT NULL,
ModifiedBy INT NOT NULL,
RoleID INT NOT NULL,
DepartmentID INT NOT NULL,
FOREIGN KEY (RoleID) REFERENCES Roles(Id),
FOREIGN KEY (DepartmentID) REFERENCES Departments(Id),
FOREIGN KEY (ModifiedBy) REFERENCES Users(Id)
)

CREATE TABLE Schedules (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Shift] VARCHAR(50) NOT NULL,
StartDate DATETIME2 NOT NULL,
EndDate DATETIME2 NOT NULL,
StartHour TIME NOT NULL,
EndHour TIME NOT NULL,
UserID INT NOT NULL,
FOREIGN KEY (UserID) REFERENCES Users(Id)
)

CREATE TABLE Vacations (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] VARCHAR(50) NOT NULL,
[Description] VARCHAR(250) NOT NULL,
[Status] VARCHAR(50) NOT NULL,
StartDate DATETIME2 NOT NULL,
EndDate DATETIME2 NOT NULL,
MainVacationHours FLOAT NOT NULL,
TimeForTimeHours FLOAT NOT NULL,
isTimeForTime BIT NOT NULL,
userID INT NOT NULL,
FOREIGN KEY (userID) REFERENCES Users(Id)
)